### ISSUE TITLE
[v5.0.0] Google SCC notifier doesn't work, 500 error

### ISSUE THREAD

**Issue by paskal** [forseti-security/terraform-google-forseti#360]
Terraform module v5.0.0 + Forseti v2.23.0 on GCE.

My notifier run fails every time ~4 hours after start according to the log:

```python
2019-10-27 18:50:47,859 INFO [forseti-security][2.23.0] google.cloud.forseti.notifier.notifiers.cscc_notifier(run): Running Cloud Security Command Center notification module.
2019-10-27 22:54:53,175 ERROR [forseti-security][2.23.0] google.cloud.forseti.services.notifier.service(_run_notifier): <HttpError 500 when requesting https://securitycenter.googleapis.com/v1/organization
s/123456789000/sources/1234567890001112223/findings?alt=json&pageToken=CusC3cy7qgAx8QqflqlfsMwLpOnD9w5itomdonX0K1oIF9Brwj8Uztlw9lYqWvw9airRnWuQUWwnucxru6Mm1ydP3pxRVGEUuePu6mj4WTsZuhYEYXO94-KsIMJdvCOyGy-QG
hY9b1EZHoFwdD-_8gAwFcoWCLafn0DCBBg8L8ICJDhItQuBASTNtQEL8J3TUi0ocpjKmt3gwsI9f0aygXMTxsT5OSmdca0-OJaoFcOPLVaXZbXjMjugvBSWlxxLVb3q-X3ZbzXe3-AhfWTRht3LLtF8d644ywr5BTKQ_8qhAIIyjKCtaSDStoimQEGw5LFd6cW4ZSF6pgIM9
CbYJGjt-vkNhMmmuOwP8JuZDFRxestHXhFw0ZDZ0xmVF6hu4i3quvoFjlUZ4_EHI8vgaD2gE_behgFt-kgbj1daMIlE5hoZaaUQujRxKBULa4NgIXTQwxWU89aV8I-E38SyZMvwm5B1QUWwvvtDON5J returned "Internal error encountered.">
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/forseti_security-2.23.0-py3.6.egg/google/cloud/forseti/services/notifier/service.py", line 129, in _run_notifier
    self.service_config)
  File "/usr/local/lib/python3.6/dist-packages/forseti_security-2.23.0-py3.6.egg/google/cloud/forseti/notifier/notifier.py", line 187, in run
    .run(violations_as_dict, source_id=source_id))
  File "/usr/local/lib/python3.6/dist-packages/forseti_security-2.23.0-py3.6.egg/google/cloud/forseti/notifier/notifiers/cscc_notifier.py", line 285, in run
    self._send_findings_to_cscc(violations, source_id=source_id)
  File "/usr/local/lib/python3.6/dist-packages/forseti_security-2.23.0-py3.6.egg/google/cloud/forseti/notifier/notifiers/cscc_notifier.py", line 229, in _send_findings_to_cscc
    for page in paged_findings_in_cscc:
  File "/usr/local/lib/python3.6/dist-packages/forseti_security-2.23.0-py3.6.egg/google/cloud/forseti/common/gcp_api/repository_mixins.py", line 55, in list
    verb_arguments=arguments):
  File "/usr/local/lib/python3.6/dist-packages/forseti_security-2.23.0-py3.6.egg/google/cloud/forseti/common/gcp_api/_base_repository.py", line 467, in execute_paged_query
    response = self._execute(request)
  File "/usr/local/lib/python3.6/dist-packages/forseti_security-2.23.0-py3.6.egg/google/cloud/forseti/common/util/replay.py", line 169, in replay_wrapper
    return f(self, request, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/forseti_security-2.23.0-py3.6.egg/google/cloud/forseti/common/util/replay.py", line 82, in record_wrapper
    return f(self, request, *args, **kwargs)
  File "/home/ubuntu/forseti-security/.eggs/retrying-1.3.3-py3.6.egg/retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "/home/ubuntu/forseti-security/.eggs/retrying-1.3.3-py3.6.egg/retrying.py", line 206, in call
    return attempt.get(self._wrap_exception)
  File "/home/ubuntu/forseti-security/.eggs/retrying-1.3.3-py3.6.egg/retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "/usr/local/lib/python3.6/dist-packages/six.py", line 693, in reraise
    raise value
  File "/home/ubuntu/forseti-security/.eggs/retrying-1.3.3-py3.6.egg/retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "/usr/local/lib/python3.6/dist-packages/forseti_security-2.23.0-py3.6.egg/google/cloud/forseti/common/gcp_api/_base_repository.py", line 541, in _execute
    num_retries=self._num_retries)
  File "/home/ubuntu/forseti-security/.eggs/google_api_python_client-1.7.10-py3.6.egg/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/ubuntu/forseti-security/.eggs/google_api_python_client-1.7.10-py3.6.egg/googleapiclient/http.py", line 855, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 500 when requesting https://securitycenter.googleapis.com/v1/organizations/123456789000/sources/1234567890001112223/findings?alt=json&pageToken=CusC3cy7qgAx8Qq
flqlfsMwLpOnD9w5itomdonX0K1oIF9Brwj8Uztlw9lYqWvw9airRnWuQUWwnucxru6Mm1ydP3pxRVGEUuePu6mj4WTsZuhYEYXO94-KsIMJdvCOyGy-QGhY9b1EZHoFwdD-_8gAwFcoWCLafn0DCBBg8L8ICJDhItQuBASTNtQEL8J3TUi0ocpjKmt3gwsI9f0aygXMTxsT
5OSmdca0-OJaoFcOPLVaXZbXjMjugvBSWlxxLVb3q-X3ZbzXe3-AhfWTRht3LLtF8d644ywr5BTKQ_8qhAIIyjKCtaSDStoimQEGw5LFd6cW4ZSF6pgIM9CbYJGjt-vkNhMmmuOwP8JuZDFRxestHXhFw0ZDZ0xmVF6hu4i3quvoFjlUZ4_EHI8vgaD2gE_behgFt-kgbj1d
aMIlE5hoZaaUQujRxKBULa4NgIXTQwxWU89aV8I-E38SyZMvwm5B1QUWwvvtDON5J returned "Internal error encountered.">
```

As a result I never see any event updates in Google SCC.

As per @hshin-g suggestion, I've decreased the number of calls for `securitycenter_max_calls` to `10`  in the `notifier` section (https://github.com/forseti-security/terraform-google-forseti/blob/e3ed110e80ee42b87f6ede1fa348c139d479dd1f/modules/server_config/templates/configs/forseti_conf_server.yaml.tpl#L277) and re-run the notifier, I'll report if that will help.

**Comment by paskal** [comment]
Decreasing the number of calls for `securitycenter_max_calls` to `10` in the `notifier` section didn't help, I've got exactly same error exactly 4 hours later after notifier start.

@hshin-g  re stackdriver logs: which ones? From which service or instance?
`cscc_source_id` is correct and was working even with Terraform `v4.3.0` for few days for me, and then broke (supposedly with the same error). Server service account permissions:
```
// project
Cloud SQL Client
Cloud Trace Agent
Service Account Token Creator
Logs Writer
Monitoring Metric Writer
Storage Object Creator
Storage Object Viewer
// organization
App Engine Viewer
BigQuery Metadata Viewer
Browser
Cloud Asset Viewer
Cloud SQL Viewer
Compute Network Viewer
Compute Security Admin
Container Analysis Notes Attacher
DLP Jobs Reader
Security Reviewer
Organization Policy Viewer
Quota Viewer
Service Usage Consumer
Stackdriver Resource Maintenance Window Editor
Stackdriver Resource Maintenance Window Viewer 
```
The link you provided specifies rights for someone enabling the SCC integration, not for server service account. The notifier successfully uploaded information to SCC before migration to Terraform, but I don't know if it's related to Forseti version upgrade or Terraform changes to server account permissions. I think that during migration to Terraform I've added a couple of organizational rights to server service account, but did not delete anything.

@kevensen SCC was enabled way before and was working all the way up to `v0.21.0` with Deployment Manager install. Then it worked after migration to Terraform `v4.3.0` (October 4 is the date of migration) and stopped working at some random point of time later (the last event update time in my SCC is October 11). SCC source ID matches the one I see in the interface and it's proven to be working.

If it's not an access rights issue, it could be related to change in amount of items in inventory or amount of security events. If that's relevant:
```
ubuntu@forseti-server-vm-xxxxxxxx:~$ forseti inventory list | grep countObjects | tail -1
  "countObjects": 606336,
```

**Comment by kevensen** [comment]
@paskal, thanks for providing that list.  A 500 error generally means an issue on the back end.  We'll investigate.  

In the mean time I think you may be missing the `Security Center Findings Editor` role at the organization level on your server service account.  Do you mind checking to see if it is applied?

**Comment by paskal** [comment]
I have this role missing on the IAM & admin page when I open it for Forseti project, however it is present for the same account when I switch to organization view. That's why I didn't include `Security Center Findings Editor` role in the list, I was looking roles under project view.

I think things were that way already when notifier was working, I did not change any service account roles after October 4.

**Comment by hshin-g** [comment]
@paskal Synced with the CSCC team on this and it looks like the requests that are being sent sent have expired page tokens, which means they are keeping page tokens for long enough before retrieving all the results, so reducing the latency between different calls to CSCC may help.

Can you try setting `securitycenter_max_calls = 1` and running that to see if you are able to get those notifications?

**Comment by paskal** [comment]
I've misread your request and set `securitycenter_max_calls = "1"` which obviously didn't resolve the problem. I'll set it to higher value and will return with result tomorrow.

**Comment by paskal** [comment]
`securitycenter_max_calls = "30"` didn't change anything as well.

For me it seems like Forseti requesting too much data in single request, when we can't afford with having amount of data we have in the cloud. I'll try to clean up existing alerts and see if issue persists.

**Comment by paskal** [comment]
@kevensen would you be so kind to move this issue to https://github.com/forseti-security/forseti-security/? Now I believe it have nothing to do with Terraform, only with forseti server itself.

**Comment by kevensen** [comment]
@paskal Closing in favor of https://github.com/forseti-security/forseti-security/issues/3425
